name: CI

on:
  push:
    branches:
      - main
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
#   test:
#     runs-on: ubuntu-latest
#
#     steps:
#       - name: Checkout master
#         uses: actions/checkout@v2
#
#       - name: Set up Python 3.9
#         uses: actions/setup-python@v2
#         with:
#           python-version: 3.9
#
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r tests/requirements.txt
#
#       - name: Lint with flake8
#         run: |
#           # stop the build if there are Python syntax errors or undefined names
#           pipenv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#           # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
#           pipenv run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
#
#       - name: Test with pytest
#         run: |
#           pytest .

  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
#     needs: test

    steps:

      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/child-growth-diary-api:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}


  deploy:
    runs-on: self-hosted
    if: github.event_name == 'push'
    needs: build

    steps:

      - name: Log in to Dockerhub
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Pulling docker image
        run: docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/child-growth-diary-api:latest

      - name: Removing all image
        run: |
          docker stop ${{ secrets.DOCKER_HUB_USERNAME }}/child-growth-diary-api:latest || true
          docker rm ${{ secrets.DOCKER_HUB_USERNAME }}/child-growth-diary-api:latest || true

      - name: Running docker as daemon
        run: docker run -p 8000:8000 ${{ secrets.DOCKER_HUB_USERNAME }}/child-growth-diary-api:latest
