name: CI

on:
  push:
    branches:
      - main
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
#   test:
#     runs-on: ubuntu-latest
#
#     steps:
#       - name: Checkout master
#         uses: actions/checkout@v2
#
#       - name: Set up Python 3.9
#         uses: actions/setup-python@v2
#         with:
#           python-version: 3.9
#
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r tests/requirements.txt
#
#       - name: Lint with flake8
#         run: |
#           # stop the build if there are Python syntax errors or undefined names
#           pipenv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#           # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
#           pipenv run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
#
#       - name: Test with pytest
#         run: |
#           pytest .

  deploy:
    runs-on: self-hosted
    if: github.event_name == 'push'
#     needs: test

    steps:
      - name: Checkout revision
        uses: actions/checkout@v2

      - name: Installing new dependencies
        run: |
          ls -la
          source ../venv/bin/activate
          pip install -U -r requirements.txt
